const Joi = require("joi");

const studentSchema = Joi.object({
    user_role: Joi.string().valid("STUDENT").required(),
    admission_no: Joi.string().required(),
    institute_id: Joi.string().required(),
    branch_id: Joi.string().required(),
    batch_id: Joi.string().required(),
    year: Joi.number().allow(''),
    academic_year: Joi.string().allow(''),
    gender: Joi.string().valid("male", "female").allow(''),
    nationality: Joi.string().allow(''),
    pincode: Joi.string().allow(''),
    state: Joi.string().allow(''), 
    city: Joi.string().allow(''),
    address: Joi.string().allow(''),
    religion: Joi.string().allow(''),
    aadhar_no: Joi.string().allow(''),
    area_name: Joi.string().allow(''),
    father_name: Joi.string().allow(''),
    mother_name: Joi.string().allow(''),
    community: Joi.string().allow(''),
    caste: Joi.string().allow(''),
    batch_name: Joi.string().required(),
    registration_type: Joi.string().allow(''),
    sats_no: Joi.string().allow(''),
    parent_mobile: Joi.string().allow(''),
    // course: Joi.array().items(
    //     Joi.object({
    //         course_id: Joi.string().required(),
    //         course_name: Joi.string().required(),
    //     })
    // ),
    room_type: Joi.string().allow(''),
    transportation_id: Joi.string().allow(''),
    hostel_id: Joi.string().allow(''),
    created_by: Joi.string().allow(''),
    remarks: Joi.string().allow(''),
    mobile: Joi.number().integer().required(),
    lastname: Joi.string().allow(''),
    firstname: Joi.string().required(),
    dob: Joi.string().allow(''),
    fees_paid: Joi.array().allow(''),
    status: Joi.string().valid("ACTIVE", "INACTIVE").required(),
    userName: Joi.string().regex(/^[\p{L}\p{M}\p{S}\p{N}\p{P}]+$/u).required(),
    password: Joi.string().allow('')
});

const teacherSchema = Joi.object({
    user_role: Joi.string().valid("TEACHER", "STAFF").required(),
    institute_id: Joi.string().required(),
    branch_id: Joi.string().required(),
    department: Joi.string().required(),
    designation: Joi.string().required(),
    gender: Joi.string().valid("male", "female"),
    blood_group: Joi.string().allow(''),
    spouse_name: Joi.string().allow(''),
    date_of_joining: Joi.string().allow(''),
    profile_pictute: Joi.string().allow(''),
    pincode: Joi.string().allow(''),
    state: Joi.string().allow(''),
    city: Joi.string().allow(''),
    address: Joi.string().allow(''),
    area_name: Joi.string().allow(''),
    emergency_connumber: Joi.number().integer(),
    emergnecy_contact_person: Joi.string().allow(''),
    educational_background: Joi.string().allow(''),
    completion_year: Joi.string().allow(''),
    expericence: Joi.string().allow(''),
    collage_cityname: Joi.string().allow(''),
    collage_name: Joi.string().allow(''),
    previous_institutename: Joi.string().allow(''),
    bank_account_no: Joi.string().allow(''),
    bank_branch: Joi.string().allow(''),
    bank_ifsc: Joi.string().allow(''),
    bank_name: Joi.string().allow(''),
    PAN_number: Joi.string().allow(''),
    PF_account_number: Joi.string().allow(''),
    EPS_account_number: Joi.string().allow(''),
    passport_expiry: Joi.string().allow(''),
    passport_no: Joi.string().allow(''),
    contract_start_date: Joi.string().allow(''),
    country_of_issue: Joi.string().allow(''),
    contract_type: Joi.string().allow(''),
    fathername: Joi.string().allow(''),
    mothername: Joi.string().allow(''),
    mobile: Joi.number().integer().required(),
    email: Joi.string().email().allow(''),
    lastname: Joi.string().allow(''),
    firstname: Joi.string().required(),
    dob: Joi.string().allow(''),
    password: Joi.string().required(),
    status: Joi.string().valid("ACTIVE", "INACTIVE").required(),
    userName: Joi.string().regex(/^[\p{L}\p{M}\p{S}\p{N}\p{P}]+$/u).required(),
});

module.exports = { studentSchema, teacherSchema };

