const Joi = require("joi");

const studentSchema = Joi.object({
    user_role: Joi.string().valid("STUDENT").required(),
    institute_id: Joi.string(),
    branch_id: Joi.string(),
    year: Joi.number(),
    academic_year: Joi.string(),
    gender: Joi.string().valid("male", "female"),
    nationality: Joi.string(),
    pincode: Joi.string(),
    state: Joi.string(),
    city: Joi.string(),
    address: Joi.string(),
    religion: Joi.string(),
    aadhar_no: Joi.string(),
    area_name: Joi.string(),
    father_name: Joi.string(),
    mother_name: Joi.string(),
    community: Joi.string(),
    caste: Joi.string(),
    batch_name: Joi.string().required(),
    registration_type: Joi.string(),
    sats_no: Joi.string(),
    parent_mobile: Joi.string(),
    course: Joi.array().items(
        Joi.object({
            course_id: Joi.string(),
            course_name: Joi.string(),
        })
    ),
    from: Joi.string(),
    to: Joi.string(),
    room_type: Joi.string(),
    transportation_id: Joi.string(),
    hostel_id: Joi.string(),
    created_by: Joi.string(),
    remarks: Joi.string(),
    mobile: Joi.number().integer().required(),
    lastname: Joi.string(),
    firstname: Joi.string().required(),
    dob: Joi.string().required,
    fees_paid: Joi.array(),
    password: Joi.string().required(),
    status: Joi.string().valid("ACTIVE", "INACTIVE").required(),
    userName: Joi.string().regex(/[\p{L}\p{M}\p{S}\p{N}\p{P}]+/u).required(),
});

const teacherSchema = Joi.object({
    user_role: Joi.string().valid("TEACHER", "STAFF").required(),
    institute_id: Joi.string(),
    branch_id: Joi.string(),
    department: Joi.string(),
    designation: Joi.string(),
    gender: Joi.string().valid("male", "female"),
    blood_group: Joi.string(),
    spouse_name: Joi.string(),
    date_of_joining: Joi.string(),
    profile_pictute: Joi.string(),
    pincode: Joi.string(),
    state: Joi.string(),
    city: Joi.string(),
    address: Joi.string(),
    area_name: Joi.string(),
    emergency_connumber: Joi.number().integer(),
    emergnecy_contact_person: Joi.string(),
    educational_background: Joi.string(),
    completion_year: Joi.string(),
    expericence: Joi.string(),
    collage_cityname: Joi.string(),
    collage_name: Joi.string(),
    previous_institutename: Joi.string(),
    bank_account_no: Joi.string(),
    bank_branch: Joi.string(),
    bank_ifsc: Joi.string(),
    bank_name: Joi.string(),
    PAN_number: Joi.string(),
    PF_account_number: Joi.string(),
    EPS_account_number: Joi.string(),
    passport_expiry: Joi.string(),
    passport_no: Joi.string(),
    contract_start_date: Joi.string(),
    country_of_issue: Joi.string(),
    contract_type: Joi.string(),
    father_name: Joi.string(),
    mother_name: Joi.string(),
    mobile: Joi.number().integer().required(),
    email: Joi.string().email().required(),
    lastname: Joi.string(),
    firstname: Joi.string().required(),
    dob: Joi.string().required(),
    password: Joi.string().required(),
    status: Joi.string().valid("ACTIVE", "INACTIVE").required(),
    userName: Joi.string().regex(/[\p{L}\p{M}\p{S}\p{N}\p{P}]+/u).required(),
});

module.exports = { studentSchema, teacherSchema };

